using Microsoft.CodeAnalysis;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Staticsoft.Contracts.ASP.Server.Generator;

[Generator]
public class ServerApiGenerator : IIncrementalGenerator
{
    const string ApiRootAttributeName = "Staticsoft.Contracts.Abstractions.ApiRootAttribute";
    const string EndpointAttributeName = "Staticsoft.Contracts.Abstractions.EndpointAttribute";
    const string HttpEndpointMetadataType = "Staticsoft.Contracts.ASP.HttpEndpointMetadata`2";
    const string GeneratedMetadataType = "Staticsoft.Contracts.ASP.GeneratedHttpEndpointMetadata`2";
    const string IEndpointRegistrationsType = "Staticsoft.Contracts.ASP.Server.IEndpointRegistrations`1";
    const string StreamableResponseMetadataType = "Staticsoft.Contracts.ASP.StreamableResponseMetadata";
    const string HttpEndpointType = "Staticsoft.Contracts.Abstractions.HttpEndpoint`2";
    const string ParametrizedHttpEndpointType = "Staticsoft.Contracts.Abstractions.ParametrizedHttpEndpoint`2";
    const string StreamableHttpEndpointType = "Staticsoft.Contracts.Abstractions.StreamableHttpEndpoint`1";
    const string StreamableParametrizedHttpEndpointType = "Staticsoft.Contracts.Abstractions.StreamableParametrizedHttpEndpoint`1";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterSourceOutput(context.CompilationProvider, static (spc, compilation) =>
        {
            var apiRootAttr = compilation.GetTypeByMetadataName(ApiRootAttributeName);
            if (apiRootAttr == null) return;

            var implementations = GetImplementations(compilation);

            foreach (var type in GetAllTypes(compilation.GlobalNamespace))
            {
                if (!type.GetAttributes().Any(a =>
                    SymbolEqualityComparer.Default.Equals(a.AttributeClass, apiRootAttr)))
                    continue;
                GenerateRegistrations(spc, compilation, type, implementations);
            }
        });
    }

    static void GenerateRegistrations(
        SourceProductionContext spc,
        Compilation compilation,
        INamedTypeSymbol apiType,
        Dictionary<string, INamedTypeSymbol> implementations)
    {
        var endpoints = GetEndpoints(compilation, apiType, string.Empty).ToList();
        var className = $"{apiType.Name}EndpointRegistrations";
        var apiTypeFull = $"global::{apiType.ToDisplayString()}";

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();
        sb.AppendLine($"internal sealed class {className}");
        sb.AppendLine($"    : global::{IEndpointRegistrationsType.Replace("`1", "")}<{apiTypeFull}>");
        sb.AppendLine("{");

        // Static metadata fields
        for (int i = 0; i < endpoints.Count; i++)
        {
            var e = endpoints[i];
            sb.AppendLine($"    static readonly global::{HttpEndpointMetadataType.Replace("`2", "")}<{e.RequestTypeFull}, {e.ResponseTypeFull}> _metadata{i} =");
            sb.AppendLine($"        new global::{GeneratedMetadataType.Replace("`2", "")}<{e.RequestTypeFull}, {e.ResponseTypeFull}>(");
            sb.AppendLine($"            \"{e.Pattern}\",");
            sb.AppendLine($"            global::Staticsoft.Contracts.ASP.PatternType.{e.PatternType},");
            sb.AppendLine($"            new global::System.Attribute[] {{ {e.AttributesCode} }});");
            sb.AppendLine();
        }

        // GetMetadata
        sb.AppendLine($"    public global::System.Collections.Generic.IEnumerable<global::Staticsoft.Contracts.ASP.HttpEndpointMetadata> GetMetadata()");
        sb.AppendLine("    {");
        for (int i = 0; i < endpoints.Count; i++)
            sb.AppendLine($"        yield return _metadata{i};");
        sb.AppendLine("    }");
        sb.AppendLine();

        // Register
        sb.AppendLine($"    public global::Microsoft.Extensions.DependencyInjection.IServiceCollection Register(");
        sb.AppendLine($"        global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
        sb.AppendLine("    {");
        for (int i = 0; i < endpoints.Count; i++)
        {
            var e = endpoints[i];
            // Register metadata as singleton
            sb.AppendLine($"        services.AddSingleton<global::{HttpEndpointMetadataType.Replace("`2", "")}<{e.RequestTypeFull}, {e.ResponseTypeFull}>>(_metadata{i});");
            // Register implementation
            if (e.ImplementationCode != null)
                sb.AppendLine($"        {e.ImplementationCode}");
        }
        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        spc.AddSource($"{className}.g.cs", sb.ToString());
    }

    sealed class EndpointEntry
    {
        public string Pattern { get; }
        public string PatternType { get; }
        public string RequestTypeFull { get; }
        public string ResponseTypeFull { get; }
        public string AttributesCode { get; }
        public string? ImplementationCode { get; }

        public EndpointEntry(string pattern, string patternType, string requestTypeFull, string responseTypeFull, string attributesCode, string? implementationCode)
        {
            Pattern = pattern;
            PatternType = patternType;
            RequestTypeFull = requestTypeFull;
            ResponseTypeFull = responseTypeFull;
            AttributesCode = attributesCode;
            ImplementationCode = implementationCode;
        }
    }

    static IEnumerable<EndpointEntry> GetEndpoints(
        Compilation compilation,
        INamedTypeSymbol type,
        string basePath)
    {
        foreach (var member in type.GetMembers().OfType<IPropertySymbol>())
        {
            if (member.Type is not INamedTypeSymbol propType) continue;
            if (IsEndpointType(compilation, propType))
                yield return CreateEntry(compilation, member, propType, basePath);
            else
                foreach (var nested in GetEndpoints(compilation, propType, $"{basePath}/{member.Name}"))
                    yield return nested;
        }
    }

    static EndpointEntry CreateEntry(
        Compilation compilation,
        IPropertySymbol property,
        INamedTypeSymbol propType,
        string basePath)
    {
        var isParametrized = IsParametrizedEndpoint(compilation, propType);
        var isStreamable = IsStreamableEndpoint(compilation, propType);
        var isStreamableParametrized = IsStreamableParametrizedEndpoint(compilation, propType);
        var patternType = (isParametrized || isStreamableParametrized) ? "Parametrized" : "Static";

        var typeArgs = propType.TypeArguments;
        string requestTypeFull = $"global::{typeArgs[0].ToDisplayString()}";
        string responseTypeFull;

        if (isStreamable || isStreamableParametrized)
            responseTypeFull = $"global::{StreamableResponseMetadataType}";
        else
            responseTypeFull = $"global::{typeArgs[1].ToDisplayString()}";

        var pattern = ComputePattern(property, basePath, isParametrized || isStreamableParametrized);
        var attributesCode = GenerateAttributesCode(property);
        var implementationCode = GenerateImplementationCode(compilation, propType, isStreamable, isStreamableParametrized);

        return new EndpointEntry(pattern, patternType, requestTypeFull, responseTypeFull, attributesCode, implementationCode);
    }

    static string ComputePattern(IPropertySymbol property, string basePath, bool isParametrized)
    {
        var endpointAttr = property.GetAttributes()
            .FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == EndpointAttributeName.Replace("Attribute", string.Empty) + "Attribute"
                              || a.AttributeClass?.MetadataName == "EndpointAttribute");

        // CallerMemberName fills pattern arg with property name at call site
        // so ConstructorArguments[1] equals property.Name unless explicitly overridden
        string patternArg = property.Name;
        if (endpointAttr != null && endpointAttr.ConstructorArguments.Length >= 2)
        {
            var arg = endpointAttr.ConstructorArguments[1];
            if (arg.Value is string s) patternArg = s;
        }

        string endpointSegment;
        if (patternArg != property.Name)
            endpointSegment = patternArg;
        else if (isParametrized)
            endpointSegment = "{parameter}";
        else
            endpointSegment = property.Name;

        return $"{basePath}/{endpointSegment}/";
    }

    static string GenerateAttributesCode(IPropertySymbol property)
    {
        var parts = new List<string>();
        foreach (var attr in property.GetAttributes())
        {
            var code = GenerateAttributeCode(attr);
            if (code != null)
                parts.Add(code);
        }
        return string.Join(", ", parts);
    }

    static string? GenerateAttributeCode(AttributeData attr)
    {
        if (attr.AttributeClass == null) return null;
        var typeFull = $"global::{attr.AttributeClass.ToDisplayString()}";

        if (!attr.ConstructorArguments.Any())
            return $"new {typeFull}()";

        var args = attr.ConstructorArguments
            .Select(TypedConstantToCode)
            .ToList();
        return $"new {typeFull}({string.Join(", ", args)})";
    }

    static string TypedConstantToCode(TypedConstant constant)
    {
        switch (constant.Kind)
        {
            case TypedConstantKind.Enum:
                var enumType = (INamedTypeSymbol)constant.Type!;
                var memberName = enumType.GetMembers()
                    .OfType<IFieldSymbol>()
                    .FirstOrDefault(f => f.HasConstantValue && Equals(f.ConstantValue, constant.Value))
                    ?.Name ?? constant.Value?.ToString() ?? "0";
                return $"global::{enumType.ToDisplayString()}.{memberName}";
            case TypedConstantKind.Primitive:
                return constant.Value switch
                {
                    string s => $"\"{s}\"",
                    bool b => b ? "true" : "false",
                    int i => i.ToString(),
                    long l => l.ToString(),
                    _ => constant.Value?.ToString() ?? "null"
                };
            case TypedConstantKind.Type:
                return $"typeof(global::{((ITypeSymbol)constant.Value!).ToDisplayString()})";
            default:
                return "null";
        }
    }

    static string? GenerateImplementationCode(
        Compilation compilation,
        INamedTypeSymbol propType,
        bool isStreamable,
        bool isStreamableParametrized)
    {
        var typeArgs = propType.TypeArguments;
        string requestFull = $"global::{typeArgs[0].ToDisplayString()}";

        if (isStreamable)
        {
            var ifaceName = $"global::{StreamableHttpEndpointType.Replace("`1", "")}<{requestFull}>";
            var implKey = GetStreamableKey(compilation, typeArgs[0]);
            if (implKey == null) return null;
            // Find implementation for StreamableHttpEndpoint<TReq>
            var impl = FindImplementation(compilation, StreamableHttpEndpointType, new[] { typeArgs[0] });
            if (impl == null) return null;
            return $"services.AddScoped<{ifaceName}, global::{impl.ToDisplayString()}>();";
        }

        if (isStreamableParametrized)
        {
            var ifaceName = $"global::{StreamableParametrizedHttpEndpointType.Replace("`1", "")}<{requestFull}>";
            var impl = FindImplementation(compilation, StreamableParametrizedHttpEndpointType, new[] { typeArgs[0] });
            if (impl == null) return null;
            return $"services.AddScoped<{ifaceName}, global::{impl.ToDisplayString()}>();";
        }

        bool isParametrized = IsParametrizedEndpoint(compilation, propType);
        string responseFull = $"global::{typeArgs[1].ToDisplayString()}";

        if (isParametrized)
        {
            var ifaceName = $"global::{ParametrizedHttpEndpointType.Replace("`2", "")}<{requestFull}, {responseFull}>";
            var impl = FindImplementation(compilation, ParametrizedHttpEndpointType, new[] { typeArgs[0], typeArgs[1] });
            if (impl == null) return null;
            return $"services.AddScoped<{ifaceName}, global::{impl.ToDisplayString()}>();";
        }
        else
        {
            var ifaceName = $"global::{HttpEndpointType.Replace("`2", "")}<{requestFull}, {responseFull}>";
            var impl = FindImplementation(compilation, HttpEndpointType, new[] { typeArgs[0], typeArgs[1] });
            if (impl == null) return null;
            return $"services.AddScoped<{ifaceName}, global::{impl.ToDisplayString()}>();";
        }
    }

    static string? GetStreamableKey(Compilation compilation, ITypeSymbol typeArg)
        => $"global::{typeArg.ToDisplayString()}";

    static INamedTypeSymbol? FindImplementation(
        Compilation compilation,
        string genericInterfaceMetadataName,
        ITypeSymbol[] typeArgs)
    {
        var ifaceDef = compilation.GetTypeByMetadataName(genericInterfaceMetadataName);
        if (ifaceDef == null) return null;

        var constructed = ifaceDef.Construct(typeArgs);
        var constructedDisplay = constructed.ToDisplayString();

        foreach (var type in GetAllAssemblyTypes(compilation.Assembly))
        {
            if (type.IsAbstract) continue;
            foreach (var iface in type.AllInterfaces)
            {
                if (iface.ToDisplayString() == constructedDisplay)
                    return type;
            }
        }
        return null;
    }

    static Dictionary<string, INamedTypeSymbol> GetImplementations(Compilation compilation)
    {
        var result = new Dictionary<string, INamedTypeSymbol>();
        foreach (var type in GetAllAssemblyTypes(compilation.Assembly))
        {
            if (type.IsAbstract) continue;
            foreach (var iface in type.AllInterfaces)
            {
                if (!iface.IsGenericType) continue;
                var defName = iface.OriginalDefinition.ToDisplayString();
                if (defName == "Staticsoft.Contracts.Abstractions.HttpEndpoint<RequestBody, ResponseBody>"
                    || defName == "Staticsoft.Contracts.Abstractions.ParametrizedHttpEndpoint<RequestBody, ResponseBody>"
                    || defName == "Staticsoft.Contracts.Abstractions.StreamableHttpEndpoint<RequestBody>"
                    || defName == "Staticsoft.Contracts.Abstractions.StreamableParametrizedHttpEndpoint<RequestBody>")
                {
                    var key = iface.ToDisplayString();
                    if (!result.ContainsKey(key))
                        result[key] = type;
                }
            }
        }
        return result;
    }

    static IEnumerable<INamedTypeSymbol> GetAllTypes(INamespaceSymbol root)
    {
        var stack = new Stack<INamespaceSymbol>();
        stack.Push(root);
        while (stack.Count > 0)
        {
            var ns = stack.Pop();
            foreach (var type in ns.GetTypeMembers())
            {
                yield return type;
                foreach (var nested in type.GetTypeMembers())
                    yield return nested;
            }
            foreach (var child in ns.GetNamespaceMembers())
                stack.Push(child);
        }
    }

    static IEnumerable<INamedTypeSymbol> GetAllAssemblyTypes(IAssemblySymbol assembly)
        => GetAllTypes(assembly.GlobalNamespace);

    static bool IsEndpointType(Compilation compilation, INamedTypeSymbol type)
    {
        if (!type.IsGenericType) return false;
        return IsHttpEndpoint(compilation, type)
            || IsParametrizedEndpoint(compilation, type)
            || IsStreamableEndpoint(compilation, type)
            || IsStreamableParametrizedEndpoint(compilation, type);
    }

    static bool IsHttpEndpoint(Compilation compilation, INamedTypeSymbol type)
        => IsOfGenericType(compilation, type, HttpEndpointType);

    static bool IsParametrizedEndpoint(Compilation compilation, INamedTypeSymbol type)
        => IsOfGenericType(compilation, type, ParametrizedHttpEndpointType);

    static bool IsStreamableEndpoint(Compilation compilation, INamedTypeSymbol type)
        => IsOfGenericType(compilation, type, StreamableHttpEndpointType);

    static bool IsStreamableParametrizedEndpoint(Compilation compilation, INamedTypeSymbol type)
        => IsOfGenericType(compilation, type, StreamableParametrizedHttpEndpointType);

    static bool IsOfGenericType(Compilation compilation, INamedTypeSymbol type, string metadataName)
    {
        if (!type.IsGenericType) return false;
        var def = compilation.GetTypeByMetadataName(metadataName);
        if (def == null) return false;
        return SymbolEqualityComparer.Default.Equals(type.OriginalDefinition, def);
    }
}
